"""
Data models for the Research Agent.

This module defines dataclasses for structured data representation throughout
the system, including video metadata, trending topics, quota state, and configuration.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import List, Dict, Any


@dataclass
class VideoMetadata:
    """Raw video data from YouTube API."""
    
    video_id: str
    title: str
    description: str
    channel_id: str
    channel_title: str
    published_at: datetime
    tags: List[str]
    view_count: int
    like_count: int
    comment_count: int
    duration: str  # ISO 8601 duration format


@dataclass
class TrendingTopic:
    """Analyzed trending topic with score, classification, and finance context."""
    
    topic_name: str
    category: str
    category_confidence: float
    trend_score: float  # 0-100
    video_count: int
    top_videos: List[VideoMetadata]
    fetched_at: datetime
    language: str = "EN"  # Language code: EN, ES, AR, OTHER
    finance_context: Dict[str, Any] = field(default_factory=dict)  # Financial intelligence
    # Multi-source fields
    source_count: int = 1  # Number of data sources reporting this topic
    sources: List[Dict[str, Any]] = field(default_factory=list)  # SourceTrend dicts
    high_confidence: bool = False  # True if 3+ sources
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        result = {
            "topic_name": self.topic_name,
            "category": self.category,
            "category_confidence": self.category_confidence,
            "trend_score": self.trend_score,
            "video_count": self.video_count,
            "language": getattr(self, '_language', self.language),  # Use detected language if available
            "top_videos": [
                {
                    "video_id": video.video_id,
                    "title": video.title,
                    "channel": video.channel_title,
                    "view_count": video.view_count,
                    "published_at": video.published_at if isinstance(video.published_at, str) else video.published_at.isoformat()
                }
                for video in self.top_videos[:5]  # Limit to 5 videos
            ],
            "fetched_at": self.fetched_at if isinstance(self.fetched_at, str) else self.fetched_at.isoformat(),
            "finance_context": self.finance_context,
            "source_count": self.source_count,
            "sources": self.sources,
            "high_confidence": self.high_confidence,
        }
        return result


@dataclass
class FinanceContext:
    """Financial context for a trending topic."""
    
    stock_tickers: List[str] = field(default_factory=list)  # e.g., ['NVDA', 'AMZN', 'MSFT']
    mentioned_companies: List[str] = field(default_factory=list)  # e.g., ['NVIDIA', 'Amazon', 'Microsoft']
    macro_relevance_score: float = 0.0  # 0-1, based on authority channel presence
    authority_channel_match: bool = False  # True if topic appears in authority content
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            'stock_tickers': self.stock_tickers,
            'mentioned_companies': self.mentioned_companies,
            'macro_relevance_score': self.macro_relevance_score,
            'authority_channel_match': self.authority_channel_match
        }


@dataclass
class SourceTrend:
    """Reference to a raw trend from a specific data source."""

    source_name: str  # "google_trends", "reddit", "yahoo_finance", "wikipedia", "youtube"
    source_url: str  # URL to the original source
    fetched_at: datetime  # When this data was fetched
    raw_data: Dict[str, Any] = field(default_factory=dict)  # Source-specific metadata

    def to_dict(self) -> Dict[str, Any]:
        return {
            "source_name": self.source_name,
            "source_url": self.source_url,
            "fetched_at": self.fetched_at.isoformat() if isinstance(self.fetched_at, datetime) else self.fetched_at,
        }


@dataclass
class StoryPitch:
    """A compelling video angle generated by GPT-4o-mini."""

    title: str  # Curiosity-driven question or angle
    hook: str  # One-sentence summary
    source_trends: List[SourceTrend]  # References to raw trend data
    context_type: str  # "recent_event" or "historic_topic"
    category: str  # Topic category
    data_note: str = ""  # Note about data availability
    estimated_interest: float = 0.0  # Ranking score (trend_score × source_count)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "title": self.title,
            "hook": self.hook,
            "source_trends": [st.to_dict() for st in self.source_trends],
            "context_type": self.context_type,
            "category": self.category,
            "data_note": self.data_note,
            "estimated_interest": self.estimated_interest,
        }


@dataclass
class StoryPitchBoard:
    """Ranked list of Story Pitches for human selection."""

    pitches: List[StoryPitch]
    generated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    source_topic_count: int = 0  # How many unified topics fed the generation

    def to_dict(self) -> Dict[str, Any]:
        return {
            "pitches": [p.to_dict() for p in self.pitches],
            "generated_at": self.generated_at.isoformat(),
            "source_topic_count": self.source_topic_count,
        }


@dataclass
class QuotaState:
    """Current state of API quota consumption."""
    
    daily_limit: int
    consumed: int
    remaining: int
    reset_at: datetime
    last_updated: datetime
    
    def usage_percentage(self) -> float:
        """Calculate quota usage as percentage."""
        return (self.consumed / self.daily_limit) * 100


@dataclass
class ResearchAgentConfig:
    """Configuration for research agent."""
    
    youtube_api_key: str
    daily_quota_limit: int = 10000
    cache_ttl_hours: int = 6
    cache_file_path: str = ".cache/topics.json"
    default_keywords: List[str] = field(default_factory=lambda: [
        "python tutorial",
        "devops automation",
        "kubernetes deployment",
        "aws cloud",
        "docker container",
        "ci/cd pipeline"
    ])
    min_trend_score: int = 30
    min_view_count: int = 1000
    search_days_back: int = 7
    max_videos_per_query: int = 50
    log_level: str = "INFO"
    structured_logging: bool = False
    
    # Macro mode configuration
    macro_mode_enabled: bool = False
    authority_channels: Dict[str, str] = field(default_factory=lambda: {
        'The Economist': 'UC0p5jTq6Xx_DosDFxVXnWaQ',
        'Bloomberg Technology': 'UCrM7B7SL_g1edFOnmj-SDKg',
        'CNBC Television': 'UCvJJ_dzjViJCoLf5uKUTwoA',
        'Financial Times': 'UCRb3vTRz8RYCqGGq-Xt8Rkw',
        'Wall Street Journal': 'UCK7tptUDHh-RYDsdxO1-5QQ',
        'TechCrunch': 'UCCjyq_K1Xwfg8Lndy7lKMpA',
        'The Verge': 'UCddiUEpeqJcYeBxX1IVBKvQ'
    })
    max_videos_per_authority_channel: int = 5
    topic_similarity_threshold: float = 0.3
    macro_bonus_multiplier: float = 2.0
    
    # Multi-source configuration
    google_trends_geo: str = ""  # Geographic filter (empty = global)
    reddit_subreddits: List[str] = field(default_factory=lambda: [
        "worldnews", "economics", "technology", "science",
        "futurology", "geopolitics", "finance",
        "dataisbeautiful", "explainlikeimfive"
    ])
    reddit_posts_per_sub: int = 25
    reddit_rate_limit_seconds: float = 2.0
    yahoo_finance_story_trigger_pct: float = 5.0  # Flag stocks moving >5%
    dedup_similarity_threshold: float = 0.75  # For cross-source dedup
    high_confidence_min_sources: int = 3
    openai_api_key: str = ""  # Loaded from OPENAI_API_KEY env var
    pitch_count: int = 12  # Target 10-15 pitches
